
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS PERMISSIONS;
DROP TABLE IF EXISTS ROLE;
DROP TABLE IF EXISTS USUARIO_ROLE;
DROP TABLE IF EXISTS RECURSO;
DROP TABLE IF EXISTS ALUNO_AVALIACAO;
DROP TABLE IF EXISTS AVALIACAO;
DROP TABLE IF EXISTS ALUNO_DISCIPLINA;
DROP TABLE IF EXISTS DISCIPLINA;
DROP TABLE IF EXISTS PROFESSOR;
DROP TABLE IF EXISTS ALUNO;
DROP TABLE IF EXISTS USUARIO;
DROP TABLE IF EXISTS CIDADE;

SET FOREIGN_KEY_CHECKS = 1;




CREATE TABLE CIDADE (
    ID_CIDADE INT AUTO_INCREMENT NOT NULL,
    COD_CIDADE VARCHAR(10) UNIQUE NOT NULL,
    NOME_CIDADE VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PK_CIDADE PRIMARY KEY (ID_CIDADE)
);

CREATE TABLE USUARIO (
    ID_USUARIO INT AUTO_INCREMENT NOT NULL,
    COD_USUARIO VARCHAR(10) UNIQUE NOT NULL,
    NOME_USUARIO VARCHAR(50),
    EMAIL VARCHAR(100),
    SENHA VARCHAR(100),
    FOTO VARCHAR(200),
    TIPO INT DEFAULT 1 NOT NULL, -- 1(PROFESSOR), 2(ALUNO)
    ID_CIDADE INT NOT NULL,
    ATIVO INT DEFAULT 1,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PK_USUARIO PRIMARY KEY (ID_USUARIO),
    CONSTRAINT FK_USUARIO_CIDADE FOREIGN KEY (ID_CIDADE) REFERENCES CIDADE(ID_CIDADE)
);

CREATE TABLE ALUNO (
    ID_ALUNO INT AUTO_INCREMENT NOT NULL,
    COD_ALUNO VARCHAR(10) UNIQUE NOT NULL,
    NOME_ALUNO VARCHAR(50),
    IDADE INT,
    ID_USUARIO INT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PK_ALUNO PRIMARY KEY (ID_ALUNO),
    CONSTRAINT FK_ALUNO_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE PROFESSOR (
    ID_PROFESSOR INT AUTO_INCREMENT NOT NULL,
    COD_PROFESSOR VARCHAR(10) UNIQUE NOT NULL,
    NOME_PROFESSOR VARCHAR(50),
    ID_USUARIO INT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PK_PROFESSOR PRIMARY KEY (ID_PROFESSOR),
    CONSTRAINT FK_PROFESSOR_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE DISCIPLINA (
    ID_DISCIPLINA INT AUTO_INCREMENT NOT NULL,
    PERIODO INT NOT NULL,
    NOME_DISCIPLINA VARCHAR(50),
    ID_PROFESSOR INT, 
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PK_DISCIPLINA PRIMARY KEY (ID_DISCIPLINA),
    CONSTRAINT FK_DISCIPLINA_PROFESSOR FOREIGN KEY (ID_PROFESSOR) REFERENCES PROFESSOR(ID_PROFESSOR)
);

CREATE TABLE ALUNO_DISCIPLINA (
    DISCIPLINA_ID INT NOT NULL,
    ALUNO_ID INT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (DISCIPLINA_ID, ALUNO_ID),
    CONSTRAINT FK_ALUNO_DISCIPLINA_DISCIPLINA FOREIGN KEY (DISCIPLINA_ID) REFERENCES DISCIPLINA(ID_DISCIPLINA),
    CONSTRAINT FK_ALUNO_DISSCIPLINA_ALUNO FOREIGN KEY (ALUNO_ID) REFERENCES ALUNO(ID_ALUNO)
);

CREATE TABLE AVALIACAO (
    ID_AVALIACAO INT AUTO_INCREMENT NOT NULL,
    DESCRICAO VARCHAR(100),
    DISCIPLINA_ID INT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PK_AVALIACAO PRIMARY KEY (ID_AVALIACAO),
    CONSTRAINT FK_AVALIACAO_DISCIPLINA FOREIGN KEY (DISCIPLINA_ID) REFERENCES DISCIPLINA(ID_DISCIPLINA)
);

CREATE TABLE ALUNO_AVALIACAO (
    ALUNO_ID INT NOT NULL,
    AVALIACAO_ID INT NOT NULL,
    NOTA DECIMAL(4, 2), 
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ALUNO_ID, AVALIACAO_ID),
    CONSTRAINT FK_ALUNO FOREIGN KEY (ALUNO_ID) REFERENCES ALUNO(ID_ALUNO),
    CONSTRAINT FK_AVALIACAO FOREIGN KEY (AVALIACAO_ID) REFERENCES AVALIACAO(ID_AVALIACAO)
);

-- TABELA PARA IMPLEMENTAÇÃO DA TÉCNICA RBAC

CREATE TABLE ROLE (
    ID_ROLE INT AUTO_INCREMENT NOT NULL,
    NOME_ROLE VARCHAR(50) UNIQUE NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PK_ROLE PRIMARY KEY (ID_ROLE)
);

CREATE TABLE USUARIO_ROLE (
    USUARIO_ID INT NOT NULL,
    ROLE_ID INT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (USUARIO_ID, ROLE_ID),
    CONSTRAINT FK_USUARIO_ROLE_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID_USUARIO),
    CONSTRAINT FK_USUARIO_ROLE_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID_ROLE)
);

CREATE TABLE RECURSO (
    ID_RECURSO INT AUTO_INCREMENT NOT NULL,
    NOME_RECURSO VARCHAR(100) UNIQUE NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PK_RECURSO PRIMARY KEY (ID_RECURSO)
);

CREATE TABLE PERMISSIONS (
    ID_PERMISSION INT AUTO_INCREMENT NOT NULL,
    ROLE_ID INT NOT NULL,
    RECURSO_ID INT NOT NULL,
    ACTION VARCHAR(20) NOT NULL,       -- CREATE, READ, UPDATE, DELETE
    POSSESSION VARCHAR(20) NOT NULL,   -- OWN ou ANY
    ATTRIBUTES VARCHAR(4000),          -- atributos permitidos (separados por vírgula)
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PK_PERMISSIONS PRIMARY KEY (ID_PERMISSION),
    CONSTRAINT FK_PERMISSIONS_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID_ROLE),
    CONSTRAINT FK_PERMISSIONS_RECURSO FOREIGN KEY (RECURSO_ID) REFERENCES RECURSO(ID_RECURSO)
);




INSERT INTO CIDADE (COD_CIDADE, NOME_CIDADE) VALUES 
('C001', 'São Paulo'),
('C002', 'Rio de Janeiro'),
('C003', 'Belo Horizonte'),
('C004', 'Curitiba'),
('C005', 'Porto Alegre'),
('C006', 'Recife'),
('C007', 'Salvador'),
('C008', 'Fortaleza'),
('C009', 'Manaus'),
('C010', 'Goiânia');


INSERT INTO USUARIO (COD_USUARIO, NOME_USUARIO, EMAIL, SENHA, TIPO, ID_CIDADE) VALUES 
('U001', 'Carlos Silva', 'carlos.silva@uni.com', '1234', 1, 1),
('U002', 'Mariana Souza', 'mariana.souza@uni.com', '1234', 1, 2),
('U003', 'João Pereira', 'joao.pereira@uni.com', '1234', 2, 3),
('U004', 'Ana Costa', 'ana.costa@uni.com', '1234', 2, 4),
('U005', 'Lucas Oliveira', 'lucas.oliveira@uni.com', '1234', 2, 5);


INSERT INTO USUARIO (COD_USUARIO, NOME_USUARIO, EMAIL, SENHA, FOTO, TIPO, ID_CIDADE) VALUES 
('U001B', 'Carlos Professor', 'carlos.prof@example.com', '1234', NULL, 1, 1),
('U002B', 'Mariana Professora', 'mariana.prof@example.com', '1234', NULL, 1, 2),
('U003B', 'Rafael Docente', 'rafael.docente@example.com', '1234', NULL, 1, 3),
('U004B', 'Fernanda Mestre', 'fernanda.mestre@example.com', '1234', NULL, 1, 4),
('U005B', 'Eduardo Instrutor', 'edu.instrutor@example.com', '1234', NULL, 1, 5);


INSERT INTO USUARIO (COD_USUARIO, NOME_USUARIO, EMAIL, SENHA, FOTO, TIPO, ID_CIDADE) VALUES 
('U006', 'João Aluno', 'joao.aluno@example.com', '1234', NULL, 2, 6),
('U007', 'Ana Aluna', 'ana.aluna@example.com', '1234', NULL, 2, 7),
('U008', 'Pedro Estudante', 'pedro.estudante@example.com', '1234', NULL, 2, 8),
('U009', 'Larissa Universitária', 'larissa.uni@example.com', '1234', NULL, 2, 9),
('U010', 'Gabriel Discente', 'gabriel.discente@example.com', '1234', NULL, 2, 10),
('U011', 'Camila Aprendiz', 'camila.aprendiz@example.com', '1234', NULL, 2, 11),
('U012', 'Rodrigo Estudante', 'rodrigo.estudante@example.com', '1234', NULL, 2, 12),
('U013', 'Beatriz Aluna', 'beatriz.aluna@example.com', '1234', NULL, 2, 13),
('U014', 'Felipe Discente', 'felipe.discente@example.com', '1234', NULL, 2, 14),
('U015', 'Isabela Estudante', 'isabela.estudante@example.com', '1234', NULL, 2, 14);

INSERT INTO PROFESSOR (COD_PROFESSOR, NOME_PROFESSOR, ID_USUARIO) VALUES 
('P001', 'Carlos Professor', 1),
('P002', 'Mariana Professora', 2);

INSERT INTO ALUNO (COD_ALUNO, NOME_ALUNO, IDADE, ID_USUARIO) VALUES 
('A001', 'João Aluno', 20, 3),
('A002', 'Ana Aluna', 22, 4),
('A003', 'Lucas Oliveira', 23, 5); 

INSERT INTO DISCIPLINA (PERIODO, NOME_DISCIPLINA, ID_PROFESSOR) VALUES 
(1, 'Banco de Dados', 1),
(1, 'Estrutura de Dados', 2),
(2, 'Inteligência Artificial', 1);

INSERT INTO ALUNO_DISCIPLINA (DISCIPLINA_ID, ALUNO_ID) VALUES 
(1, 1),
(3, 1),
(2, 2),
(1, 3);

INSERT INTO AVALIACAO (DESCRICAO, DISCIPLINA_ID) VALUES 
('Prova 1 - Banco de Dados', 1),
('Prova 1 - Estrutura de Dados', 2),
('Trabalho - Inteligência Artificial', 3);

INSERT INTO ALUNO_AVALIACAO (ALUNO_ID, AVALIACAO_ID, NOTA) VALUES 
(1, 1, 8.5),
(1, 3, 9.0),
(2, 2, 7.5),
(3, 1, 6.8);

INSERT INTO ROLE (NOME_ROLE) VALUES 
('ADMIN'),
('PROFESSOR'),
('ALUNO');

INSERT INTO USUARIO_ROLE (USUARIO_ID, ROLE_ID) VALUES 
(1, 1),
(1, 2),
(2, 2),
(3, 3),
(4, 3);

INSERT INTO RECURSO (NOME_RECURSO) VALUES 
('USUARIOS'),
('ALUNOS'),
('PROFESSORES'),
('CIDADES');

INSERT INTO PERMISSIONS (ROLE_ID, RECURSO_ID, ACTION, POSSESSION, ATTRIBUTES) VALUES 
(1, 1, 'CREATE', 'ANY', '*'),
(1, 1, 'READ', 'ANY', '*'),
(1, 1, 'UPDATE', 'ANY', '*'),
(1, 1, 'DELETE', 'ANY', '*'),
(2, 3, 'READ', 'OWN', 'NOME_PROFESSOR,ID_USUARIO'),
(2, 3, 'UPDATE', 'OWN', 'NOME_PROFESSOR'),
(3, 2, 'READ', 'OWN', 'NOME_ALUNO,IDADE');